/*
 * This source file was generated by the Gradle 'init' task
 */
package org.loadtesting;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        LoadTestRun classUnderTest = new LoadTestRun();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
