/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.google.code.gson:gson:2.11.0")
    implementation("org.xerial:sqlite-jdbc:3.46.0.0")

    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.10.2")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    mainClass.set("org.loadtesting.LoadTestRun")
    applicationDefaultJvmArgs = listOf(
        "-Dthreads=${System.getProperty("threads", "classic")}",
        "-Dparser=${System.getProperty("parser", "own")}"
    )
}

tasks.register<JavaExec>("runServer") {
    group = "application"
    description = "Run HTTP Server"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("org.httpServerAyzek.RunServer")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
